def display_bill(customer, units, bill):
    print("\n========================================")
    print("              ELECTRICITY BILL")
    print("========================================")
    print(f"Customer Name : {customer['name']}")
    print(f"Consumer ID   : {customer['consumer_id']}")
    print(f"Units Used    : {units}")
    print("----------------------------------------")
    print(f"Energy Charge : Rs. {bill['energy_charge']:.2f}")
    print(f"Fixed Charge  : Rs. {bill['fixed_charge']:.2f}")
    print(f"Surcharge     : Rs. {bill['surcharge']:.2f}")
    print("----------------------------------------")
    print(f"TOTAL BILL    : Rs. {bill['total']:.2f}")
    print("========================================")